import React, { useState } from "react";
import { Sparkles, RefreshCw, Copy, Check, Printer, FileText } from "lucide-react";
import { DashboardData } from "../types";

interface Props {
  data: DashboardData | null;
}

export default function ExecutiveAnalysis({ data }: Props) {
  const [analysis, setAnalysis] = useState<string>("");
  const [loading, setLoading] = useState<boolean>(false);
  const [copied, setCopied] = useState<boolean>(false);

  const fetchAnalysis = async () => {
    if (!data) return;
    setLoading(true);
    try {
      const response = await fetch("/api/netsuite/analysis", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ financeData: data }),
      });
      if (response.ok) {
        const result = await response.json();
        setAnalysis(result.analysis);
      } else {
        setAnalysis("Failed to generate executive analysis. Please check your credentials or network.");
      }
    } catch (err: any) {
      setAnalysis(`Error generating commentary: ${err.message || err}`);
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(analysis);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;
    printWindow.document.write(`
      <html>
        <head>
          <title>Executive Financial Commentary - NetSuite</title>
          <style>
            body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; padding: 40px; color: #333; line-height: 1.6; }
            h3 { border-bottom: 2px solid #ccc; padding-bottom: 10px; margin-top: 30px; font-size: 1.5rem; }
            ul { padding-left: 20px; }
            li { margin-bottom: 8px; }
            code { background: #f4f4f4; padding: 2px 4px; font-family: monospace; }
          </style>
        </head>
        <body>
          <h2>Executive CFO Commentary & Board Briefing</h2>
          <hr />
          <div>${analysis.replace(/\n/g, "<br/>")}</div>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  return (
    <div id="executive-analysis-panel" className="bg-white border border-slate-200 rounded-xl p-6 shadow-xs mb-6">
      <div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-100 pb-4 mb-5">
        <div>
          <div className="flex items-center gap-2">
            <span className="p-1 rounded bg-slate-100 text-slate-800 border border-slate-200">
              <Sparkles className="w-4 h-4 text-amber-500" />
            </span>
            <h3 className="font-display font-bold text-lg text-slate-900">AI CFO Board Narrative & Analysis</h3>
          </div>
          <p className="text-xs text-slate-500 mt-1">
            Instantly formulate board-level analytical briefs and insights on active NetSuite reports using server-side Claude intelligence.
          </p>
        </div>

        {!analysis && !loading && (
          <button
            onClick={fetchAnalysis}
            className="flex items-center gap-2 px-4 py-2 rounded-lg bg-slate-900 hover:bg-slate-800 text-xs font-semibold text-white transition-all shadow-sm cursor-pointer"
          >
            <Sparkles className="w-3.5 h-3.5 text-amber-300" />
            Generate Board Narrative
          </button>
        )}
      </div>

      {loading && (
        <div className="flex flex-col items-center justify-center py-12 text-center space-y-4">
          <RefreshCw className="w-8 h-8 text-slate-700 animate-spin" />
          <div className="space-y-1">
            <p className="text-sm font-bold text-slate-900 font-display">Analyzing Financial Statements...</p>
            <p className="text-xs text-slate-500 max-w-sm">
              Cross-referencing Revenue actuals, balance sheet liquidity ratios, and cash runway projections.
            </p>
          </div>
        </div>
      )}

      {analysis && !loading && (
        <div className="space-y-4">
          <div className="bg-slate-50 border border-slate-200 p-5 rounded-xl text-slate-700 text-xs leading-relaxed font-sans space-y-3 whitespace-pre-wrap max-h-[350px] overflow-y-auto font-medium">
            {analysis}
          </div>

          <div className="flex items-center justify-between pt-2 border-t border-slate-100">
            <span className="text-[10px] text-slate-500 flex items-center gap-1 font-semibold">
              <FileText className="w-3 h-3 text-slate-400" /> Generated by Claude Analytical Engine
            </span>

            <div className="flex gap-2">
              <button
                onClick={handleCopy}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded bg-slate-100 hover:bg-slate-200 text-slate-700 hover:text-slate-950 border border-slate-200 transition-all text-[11px] font-semibold cursor-pointer"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5 text-slate-500" />}
                {copied ? "Copied" : "Copy Brief"}
              </button>
              <button
                onClick={handlePrint}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded bg-slate-100 hover:bg-slate-200 text-slate-700 hover:text-slate-950 border border-slate-200 transition-all text-[11px] font-semibold cursor-pointer"
              >
                <Printer className="w-3.5 h-3.5 text-slate-500" />
                Print Brief
              </button>
              <button
                onClick={fetchAnalysis}
                className="flex items-center gap-1 px-3 py-1.5 rounded bg-blue-50 hover:bg-blue-100 text-blue-700 border border-blue-100 transition-all text-[11px] font-semibold cursor-pointer"
              >
                <RefreshCw className="w-3.5 h-3.5 mr-1 text-blue-600" />
                Regenerate
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
